name: build

# Trigger on pull requests
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: |
        echo Installing...
        yarn install
        
    - name: Build
      run: |
        echo Building...
        yarn build
